### ISSUE TITLE
package.json is missing dependency list

### ISSUE THREAD

**Issue by andirotter** [MayGo/backer-timetracker#2]
Hey,

i cloned the repo and did a "npm install" and afterwards a "gulp". App didn't start up, complaining about missing installed modules. I looked up the recent changes and wondered, why the "dependencies" section is missing in the package.json. Maybe you have a look into this.

Regards

**Comment by MayGo** [comment]
I use two package.json structure as is recommended in electron-builder:
https://github.com/electron-userland/electron-builder#two-packagejson-structure
I should update this project readme.

2016-07-04 15:02 GMT+03:00 Andreas Rotter <notifications@github.com>:
